name: ci
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install MDBook
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - name: Generate documentation
        uses: ryankurte/action-mdbook@0.1.1
        with:
          outputDir: book
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
