name: ci
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions: 'read-all|write-all'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MDBook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz

      - name: Generate documentation
        run: |
          ./mdbook build --dest-dir build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
